# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Trigger the workflow on push or pull requests events but only for the "master" branch
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can sequentially or in parallel jobs:
jobs:
  # This worklfow contains a sible job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of taska that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your jib can acces it
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: 6.0.100
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet rest
